# fly.toml app configuration file generated for sjwc-n8n on 2024-05-13T16:32:10-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sjwc-n8n'
primary_region = 'iad'

[build]
  image = 'n8nio/n8n'

[env]
  EXECUTIONS_DATA_MAX_AGE = '168'
  EXECUTIONS_DATA_PRUNE = 'true'
  EXECUTIONS_DATA_PRUNE_MAX_COUNT = '10000'
  GENERIC_TIMEZONE = 'America/Chicago'
  N8N_DIAGNOSTICS_ENABLED = 'false'
  N8N_HIRING_BANNER_ENABLED = 'false'
  N8N_HOST = 'sjwc-n8n.fly.dev'
  N8N_PORT = '8080'
  N8N_PROTOCOL = 'https'
  TINI_SUBREAPER = 'true'
  WEBHOOK_URL = 'https://sjwc-n8n.fly.dev'

[[mounts]]
  source = 'n8n_vol'
  destination = '/home/node/.n8n'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1
